name: GTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install build dependencies
      run: sudo apt-get install libboost-dev
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build project
      run:  cmake --build build
    - name: Run Tests
      run: cd build/src/test && ./VDSProject_test
    - name: Run Reachability Tests
      run: cd build/src/reachability && ./VDSProject_reachability
